version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
     - .:/code
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      - APP_BACKEND_URL=backend:5000
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/src
